import { MODULE_ID, FLAG_KEY, THEMES, DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE } from "./constants.js";
import { LocalStore } from "./storage.js";
import { getThemeName, getCustomTheme, getNotificationSound } from "./settings.js";
import { attachmentFromDrop, claimItem, openDocument } from "./attachments.js";
import { MausritterAdapter } from "./adapters/mausritter.js";

const esc=v=>foundry.utils.escapeHTML(String(v??""));
const fOf=m=>{try{return m.getFlag(MODULE_ID,FLAG_KEY);}catch{return null;}};
const time=m=>Number(m?.timestamp??m?._source?.timestamp??0)||0;

export class TelegramApp {
  constructor(index,messages,rolls) {
    this.index=index; this.messages=messages; this.rolls=rolls; this.root=null; this.launcher=null; this.selectedPlayerId=null; this.loaded=0; this.reply=null; this.readTimes={}; this.liveReads=new Map(); this.saveReadTimer=null;
  }
  t(k,d={}) { return game.i18n.format(k,d); }
  async playSound() {
    if (!game.settings.get(MODULE_ID,"sound")) return;
    try {
      const { src } = getNotificationSound();
      foundry.audio.AudioHelper.play({ src, volume: 0.8, autoplay: true, loop: false, channel: "interface" }, false);
    } catch {}
  }
  channelId() { const id=game.user.isGM?this.selectedPlayerId:game.user.id; return id?this.messages.channelId(id):null; }
  players() { return game.users.filter(u=>!u.isGM).sort((a,b)=>(a.active===b.active?a.name.localeCompare(b.name):a.active?-1:1)); }
  currentPlayer() { return game.user.isGM?game.users.get(this.selectedPlayerId):game.user; }
  userImg(user) { const a=user?.character; return a?.img||user?.avatar||"icons/svg/mystery-man.svg"; }
  readFlag(user,channelId) { const x=user?.getFlag?.(MODULE_ID,"reads"); return Number(x?.[channelId]??0)||0; }
  myRead(channelId) { return Number(this.readTimes[channelId]??this.readFlag(game.user,channelId))||0; }
  latestIncoming(channelId) { let latest=0; for(const m of this.index.messages(channelId,{visibleOnly:false})) { const f=fOf(m); if(f?.senderId && f.senderId!==game.user.id) latest=Math.max(latest,time(m)); } return latest; }
  unread(channelId) { const last=this.myRead(channelId); return this.index.messages(channelId).filter(m=>{const f=fOf(m);return f?.senderId!==game.user.id && time(m)>last;}).length; }
  allUnread() { return this.players().reduce((n,p)=>n+this.unread(this.messages.channelId(p.id)),0); }
  async loadReadState() { this.readTimes=foundry.utils.deepClone(game.user.getFlag(MODULE_ID,"reads")??{}); }
  markRead(channelId) {
    const latest=this.latestIncoming(channelId); if(!latest || latest<=this.myRead(channelId)) return;
    this.readTimes[channelId]=latest; clearTimeout(this.saveReadTimer);
    this.saveReadTimer=setTimeout(()=>game.user.setFlag(MODULE_ID,"reads",foundry.utils.deepClone(this.readTimes)).catch(()=>{}),500);
    game.socket.emit(`module.${MODULE_ID}`,{type:"read",userId:game.user.id,channelId,timestamp:latest});
  }
  receiptState(message) {
    const f=fOf(message); if(f?.senderId!==game.user.id) return "";
    const ch=f.channelId; let read=0,active=false;
    if(game.user.isGM) { const p=game.users.get(f.playerId); read=Math.max(this.readFlag(p,ch),Number(this.liveReads.get(`${p?.id}:${ch}`)??0)); active=!!p?.active; }
    else { for(const g of game.users.filter(u=>u.isGM)){read=Math.max(read,this.readFlag(g,ch),Number(this.liveReads.get(`${g.id}:${ch}`)??0)); active ||= !!g.active;} }
    return read>=time(message)?"read":active?"delivered":"sent";
  }
  receipt(message) { const st=this.receiptState(message); return st?this.t(`MRTelegram.Status.${st[0].toUpperCase()+st.slice(1)}`):""; }
  metaHTML(m) {
    const tm=new Date(time(m)).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}), st=this.receiptState(m);
    return st?`${tm} <span class="mrt-tick" data-state="${st}"><i class="fas ${st==="sent"?"fa-check":"fa-check-double"}" aria-hidden="true"></i> ${esc(this.receipt(m))}</span>`:tm;
  }
  themeVars() {
    const name=getThemeName(); if(name==="custom") return {...THEMES.modern.vars,...getCustomTheme()}; return THEMES[name]?.vars??THEMES.modern.vars;
  }
  applyTheme() {
    for(const el of [this.launcher,this.root]) if(el) for(const [k,v] of Object.entries(this.themeVars())) el.style.setProperty(k,v);
    if(!this.root) return;
    this.root.classList.toggle("mrt-contrast",game.settings.get(MODULE_ID,"highContrast"));
    this.root.classList.toggle("mrt-reading",game.settings.get(MODULE_ID,"readingMode"));
    this.root.classList.toggle("mrt-reduce",game.settings.get(MODULE_ID,"reduceMotion"));
    this.root.dataset.scale=game.settings.get(MODULE_ID,"textScale"); this.root.dataset.theme=getThemeName();
  }
  ensureLauncher() {
    let b=document.getElementById("mr-telegram-launcher");
    if(!b){
      b=document.createElement("button"); b.id="mr-telegram-launcher"; b.type="button"; b.setAttribute("aria-label","MR- Telegram"); b.title="MR- Telegram";
      b.innerHTML=`<i class="fas fa-envelope" aria-hidden="true"></i><span>MR</span><b aria-hidden="true"></b>`;
      document.body.appendChild(b); this.bindLauncher(b);
    }
    this.launcher=b; this.applyTheme(); this.updateLauncher();
  }
  bindLauncher(b) {
    const pos=LocalStore.getJSON("launcher",null);
    if(pos&&Number.isFinite(pos.left)&&Number.isFinite(pos.top)) this.placeLauncher(b,pos.left,pos.top);
    let sx=0,sy=0,sl=0,st=0,down=false,moved=false;
    b.addEventListener("pointerdown",e=>{if(e.button)return;down=true;moved=false;const r=b.getBoundingClientRect();sx=e.clientX;sy=e.clientY;sl=r.left;st=r.top;b.setPointerCapture?.(e.pointerId);});
    b.addEventListener("pointermove",e=>{if(!down)return;if(!moved&&Math.hypot(e.clientX-sx,e.clientY-sy)<5)return;moved=true;this.placeLauncher(b,sl+e.clientX-sx,st+e.clientY-sy);});
    const end=()=>{if(down&&moved){const r=b.getBoundingClientRect();LocalStore.setJSON("launcher",{left:r.left,top:r.top});}down=false;};
    b.addEventListener("pointerup",end); b.addEventListener("pointercancel",end);
    b.addEventListener("click",()=>{if(moved){moved=false;return;}this.open();});
    window.addEventListener("resize",()=>{const r=b.getBoundingClientRect();if(b.style.left)this.placeLauncher(b,r.left,r.top);});
  }
  placeLauncher(b,left,top) {
    const x=Math.max(4,Math.min(innerWidth-b.offsetWidth-4,left)), y=Math.max(4,Math.min(innerHeight-b.offsetHeight-4,top));
    Object.assign(b.style,{left:`${x}px`,top:`${y}px`,right:"auto",bottom:"auto"});
  }
  updateLauncher(pulse=false) { if(!this.launcher)return; const n=this.allUnread(); this.launcher.querySelector("b").textContent=n?n>99?"99+":String(n):"";this.launcher.classList.toggle("has-unread",n>0);if(pulse){this.launcher.classList.remove("pulse");void this.launcher.offsetWidth;this.launcher.classList.add("pulse");} }
  open() {
    if(this.root){this.root.hidden=false;this.root.style.display="flex";this.clampWindow();this.applyTheme();this.renderAll();this.root.querySelector(".mrt-input")?.focus();return;}
    if(game.user.isGM&&!this.selectedPlayerId)this.selectedPlayerId=this.players()[0]?.id??null;
    const root=document.createElement("section"); root.id="mr-telegram-app"; root.className="mrt-app"; root.setAttribute("role","dialog"); root.setAttribute("aria-label","MR- Telegram"); root.innerHTML=this.shellHTML(); document.body.appendChild(root); this.root=root; this.applyWindow(); this.bind(); this.applyTheme(); this.renderAll(); this.root.querySelector(".mrt-input")?.focus();
  }
  close(){if(this.root)this.root.style.display="none";this.updateLauncher();}
  shellHTML(){
    const tt=k=>esc(this.t(k)), gm=game.user.isGM;
    const btn=(act,icon,key)=>`<button type="button" data-act="${act}" title="${tt(key)}" aria-label="${tt(key)}"><i class="fas ${icon}" aria-hidden="true"></i></button>`;
    return `<header class="mrt-top"><button type="button" class="mrt-brand" data-act="theme" title="${tt("MRTelegram.Tooltip.Theme")}" aria-label="${tt("MRTelegram.Tooltip.Theme")}"><i class="fas fa-envelope" aria-hidden="true"></i></button><div class="mrt-title"><strong>MR- TELEGRAM</strong><small>${tt("MRTelegram.Subtitle")}</small></div><div class="mrt-top-actions">${btn("search","fa-search","MRTelegram.Search")}${gm?btn("bulk","fa-users","MRTelegram.Bulk")+btn("templates","fa-bolt","MRTelegram.Templates"):""}${btn("access","fa-universal-access","MRTelegram.Accessibility")}${btn("close","fa-times","MRTelegram.Close")}</div></header><div class="mrt-body">${gm?`<aside class="mrt-side" aria-label="${tt("MRTelegram.Conversations")}"></aside>`:""}<main class="mrt-main"><div class="mrt-chat-head"></div><div class="mrt-pinned"></div><div class="mrt-messages" role="log" aria-live="polite"></div><div class="mrt-compose"></div></main></div>`;
  }
  bind(){
    this.root.addEventListener("click",e=>this.onClick(e)); this.root.addEventListener("keydown",e=>{if(e.target?.matches(".mrt-input")&&e.key==="Enter"&&!e.shiftKey&&!e.isComposing){e.preventDefault();this.sendCurrent();return;}if(e.key==="Escape"){const m=this.root.querySelector(".mrt-modal-wrap:last-of-type");if(m){m.remove();e.stopPropagation();this.root.querySelector(".mrt-input")?.focus();}}});
    this.root.addEventListener("input",e=>{if(e.target?.matches(".mrt-input")){LocalStore.setDraft(this.channelId(),e.target.value);}});
    this.root.addEventListener("dragover",e=>{if(e.target.closest(".mrt-main")){e.preventDefault();this.root.querySelector(".mrt-drop")?.classList.add("hot");}});
    this.root.addEventListener("dragleave",e=>{if(!this.root.contains(e.relatedTarget))this.root.querySelector(".mrt-drop")?.classList.remove("hot");});
    this.root.addEventListener("drop",async e=>{if(!e.target.closest(".mrt-main"))return;e.preventDefault();this.root.querySelector(".mrt-drop")?.classList.remove("hot");try{const a=await attachmentFromDrop(e);await this.messages.sendAttachment(this.currentPlayer().id,a);}catch(err){ui.notifications.warn(this.t(`MRTelegram.Errors.${err.message==="too-large"?"ImageTooLarge":"Drop"}`));}});
    this.bindDrag(); let t=0; new ResizeObserver(()=>{clearTimeout(t);t=setTimeout(()=>this.saveWindow(),250);}).observe(this.root);
  }
  bindDrag(){const h=this.root.querySelector(".mrt-top");let drag=false,sx=0,sy=0,sl=0,st=0;h.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;drag=true;const r=this.root.getBoundingClientRect();sx=e.clientX;sy=e.clientY;sl=r.left;st=r.top;h.setPointerCapture?.(e.pointerId);});h.addEventListener("pointermove",e=>{if(!drag)return;this.root.style.left=`${Math.max(0,Math.min(innerWidth-this.root.offsetWidth,sl+e.clientX-sx))}px`;this.root.style.top=`${Math.max(0,Math.min(innerHeight-50,st+e.clientY-sy))}px`;});const stop=()=>{if(drag){drag=false;this.saveWindow();}};h.addEventListener("pointerup",stop);h.addEventListener("pointercancel",stop);}
  applyWindow(){const s=LocalStore.getWindow();if(s){for(const k of ["left","top","width","height"])if(Number.isFinite(s[k]))this.root.style[k]=`${s[k]}px`;}this.clampWindow();}
  clampWindow(){const r=this.root.getBoundingClientRect();if(!r.width)return;const w=Math.min(r.width,innerWidth-8),h=Math.min(r.height,innerHeight-8);if(w<r.width)this.root.style.width=`${w}px`;if(h<r.height)this.root.style.height=`${h}px`;this.root.style.left=`${Math.max(0,Math.min(innerWidth-w,r.left))}px`;this.root.style.top=`${Math.max(0,Math.min(innerHeight-h,r.top))}px`;}
  saveWindow(){if(!this.root||this.root.style.display==="none")return;const r=this.root.getBoundingClientRect();LocalStore.setWindow({left:r.left,top:r.top,width:r.width,height:r.height});}
  renderAll(){this.renderSidebar();this.renderHeader();this.renderPinned();this.renderThread();this.renderCompose();this.markRead(this.channelId());this.updateLauncher();}
  lastOf(ch){const l=this.index.messages(ch);return l[l.length-1]??null;}
  renderSidebar(){const box=this.root?.querySelector(".mrt-side");if(!box)return;box.innerHTML=`<div class="mrt-side-title">${esc(this.t("MRTelegram.Conversations"))}</div>`+this.players().map(p=>{const ch=this.messages.channelId(p.id),n=this.unread(ch),last=this.lastOf(ch),pv=last?(fOf(last)?.senderId===game.user.id?`${esc(this.t("MRTelegram.You"))}: `:"")+esc(this.summary(last,60)):esc(this.t("MRTelegram.NoMessages"));return `<button type="button" class="mrt-person ${p.id===this.selectedPlayerId?"sel":""} ${n?"unread":""}" data-player="${p.id}"><i class="mrt-avatar ${p.active?"on":""}"><img src="${esc(this.userImg(p))}" alt=""></i><span><strong>${esc(p.name)}</strong><small>${pv}</small></span>${n?`<b aria-label="${n}">${n>99?"99+":n}</b>`:""}</button>`;}).join("");}
  renderHeader(){const box=this.root?.querySelector(".mrt-chat-head");if(!box)return;const p=this.currentPlayer();if(!p){box.innerHTML=`<div>${esc(this.t("MRTelegram.SelectPlayer"))}</div>`;return;} const target=game.user.isGM?p:game.users.find(u=>u.isGM&&u.active)??game.users.find(u=>u.isGM);box.innerHTML=`<i class="mrt-avatar ${target?.active?"on":""}"><img src="${esc(this.userImg(target))}" alt=""></i><div><strong>${esc(target?.name??this.t("MRTelegram.GM"))}</strong><small>${esc(game.user.isGM?this.t("MRTelegram.PrivateChannelPlayer",{name:p.name}):this.t("MRTelegram.PrivateChannelGM"))}</small></div><div class="mrt-head-actions"><button type="button" data-act="roll"><i class="fas fa-dice-d20" aria-hidden="true"></i> ${esc(this.t("MRTelegram.SecretRoll"))}</button>${game.user.isGM&&MausritterAdapter.matches()?`<button type="button" data-act="mausritter-save"><i class="fas fa-shield-alt" aria-hidden="true"></i> ${esc(this.t("MRTelegram.MausritterSave"))}</button>`:""}${game.user.isGM?`<button type="button" data-act="notes" title="${esc(this.t("MRTelegram.Notes"))}" aria-label="${esc(this.t("MRTelegram.Notes"))}"><i class="fas fa-sticky-note" aria-hidden="true"></i></button><button type="button" data-act="clear" class="danger" title="${esc(this.t("MRTelegram.Clear"))}" aria-label="${esc(this.t("MRTelegram.Clear"))}"><i class="fas fa-eraser" aria-hidden="true"></i></button>`:""}</div>`;}
  renderPinned(){const box=this.root?.querySelector(".mrt-pinned");if(!box)return;const ch=this.channelId();if(!ch){box.innerHTML="";return;}const p=this.index.messages(ch).filter(m=>fOf(m)?.pinned).slice(-5);box.innerHTML=p.length?`<div class="mrt-pinned-title"><i class="fas fa-thumbtack"></i> ${esc(this.t("MRTelegram.Pinned"))}</div>`+p.map(m=>`<button data-act="jump" data-mid="${m.id}">${esc(this.summary(m,100))}</button>`).join(""):"";}
  pageSize(){return Math.min(MAX_PAGE_SIZE,Math.max(50,Number(game.settings.get(MODULE_ID,"pageSize"))||DEFAULT_PAGE_SIZE));}
  renderThread({preserveScroll=false}={}){const box=this.root?.querySelector(".mrt-messages");if(!box)return;const ch=this.channelId();if(!ch){box.innerHTML=`<div class="mrt-empty">${esc(this.t("MRTelegram.SelectPlayer"))}</div>`;return;}const all=this.index.messages(ch),limit=Math.min(all.length,this.pageSize()+this.loaded),list=all.slice(-limit);const oldHeight=box.scrollHeight,oldTop=box.scrollTop;box.innerHTML=(all.length>list.length?`<button class="mrt-load-old" data-act="older">${esc(this.t("MRTelegram.LoadOlder"))}</button>`:"")+ (list.length?this.threadHTML(list):`<div class="mrt-empty"><i class="fas fa-envelope-open-text" aria-hidden="true"></i><span>${esc(this.t("MRTelegram.NoMessages"))}</span></div>`);if(preserveScroll)box.scrollTop=oldTop+(box.scrollHeight-oldHeight);else requestAnimationFrame(()=>box.scrollTop=box.scrollHeight);this.freshId=null;}
  dayLabel(ts){const d=new Date(ts),n=new Date(),day=x=>new Date(x.getFullYear(),x.getMonth(),x.getDate()).getTime(),diff=Math.round((day(n)-day(d))/864e5);if(diff===0)return this.t("MRTelegram.Today");if(diff===1)return this.t("MRTelegram.Yesterday");return d.toLocaleDateString(game.i18n.lang,{weekday:"long",day:"numeric",month:"long"});}
  threadHTML(list){let out="",prevDay="",prev=null;for(const m of list){const dk=new Date(time(m)).toDateString(),fresh=dk!==prevDay,h=this.messageHTML(m,fresh?null:prev);if(!h)continue;if(fresh){out+=`<div class="mrt-day"><span>${esc(this.dayLabel(time(m)))}</span></div>`;prevDay=dk;}out+=h;prev=m;}return out;}
  summary(m,max=120){const f=fOf(m);let s=f?.text||f?.label||f?.note||f?.attachment?.name||f?.kind||"";s=String(s).replace(/\s+/g," ").trim();return s.length>max?s.slice(0,max-1)+"…":s;}
  msgTools(m){const f=fOf(m);return `<div class="mrt-msgtools"><button type="button" data-act="reply" data-mid="${m.id}" title="${esc(this.t("MRTelegram.Reply"))}" aria-label="${esc(this.t("MRTelegram.Reply"))}"><i class="fas fa-reply" aria-hidden="true"></i></button>${game.user.isGM?`<button type="button" data-act="pin" data-mid="${m.id}" title="${esc(this.t("MRTelegram.Pin"))}" aria-label="${esc(this.t("MRTelegram.Pin"))}"><i class="fas fa-thumbtack" aria-hidden="true"></i></button>`:""}</div>`;}
  messageHTML(m,prev=null){
    const f=fOf(m);if(!f)return"";const mine=f.senderId===game.user.id;
    const head=(icon,text)=>`<div class="mrt-card-head"><i class="fas ${icon}" aria-hidden="true"></i><strong>${esc(text)}</strong></div>`;
    const res=ok=>ok===true?this.t("MRTelegram.Success"):ok===false?this.t("MRTelegram.Failure"):this.t("MRTelegram.Result");
    const badge=ok=>`<span class="mrt-badge ${ok===true?"ok":ok===false?"ko":""}">${esc(res(ok))}</span>`;
    const btn=(act,label,cls="")=>`<button type="button" class="${cls}" data-act="${act}" data-mid="${m.id}">${esc(label)}</button>`;
    let body="",card=true;
    if(f.kind==="text"){card=false;body=`${f.replyTo?`<blockquote><b>${esc(f.replyTo.senderName??"")}</b>${esc(f.replyTo.text??"")}</blockquote>`:""}<div class="mrt-text">${esc(f.text).replace(/\n/g,"<br>")}</div>`;}
    else if(f.kind==="attachment"){const a=f.attachment??{},src=a.src||a.img;body=`${src?`<img class="mrt-preview" src="${esc(src)}" alt="" data-act="image" data-mid="${m.id}">`:""}${head("fa-paperclip",a.name??this.t("MRTelegram.Attachment"))}<div class="mrt-card-actions">${a.uuid?btn("open-doc",this.t("MRTelegram.Open")):""}${a.url?btn("open-link",this.t("MRTelegram.OpenLink")):""}${!game.user.isGM&&a.documentType==="Item"&&a.itemData&&f.senderId!==game.user.id?btn("claim",this.t("MRTelegram.Claim"),"accent"):""}</div>`;}
    else if(f.kind==="roll-request")body=`${head("fa-dice-d20",f.label??this.t("MRTelegram.SecretRoll"))}${f.description?`<p>${esc(f.description)}</p>`:""}<div class="mrt-card-actions">${!game.user.isGM&&f.status==="pending"?btn("execute-roll",this.t("MRTelegram.Roll"),"accent"):`<span class="mrt-state">${esc(this.t(`MRTelegram.RollStatus.${f.status||"pending"}`))}</span>`}</div>`;
    else if(f.kind==="roll-result"){if(!game.user.isGM)return"";body=`${head("fa-eye",this.t("MRTelegram.GMOnlyResult"))}<p>${esc(f.label)} = <b class="mrt-total">${f.total}</b> ${badge(f.success)}</p>${f.status!=="revealed"?`<div class="mrt-card-actions">${btn("reveal-outcome",this.t("MRTelegram.RevealOutcome"))}${btn("reveal-full",this.t("MRTelegram.RevealFull"))}</div>`:""}`;}
    else if(f.kind==="roll-reveal")body=`${head("fa-dice-d20",f.label)}<p>${f.revealMode==="full"?`<b class="mrt-total">${f.total}</b> `:""}${badge(f.success)}</p>`;
    else if(f.kind==="save-request")body=`${head("fa-shield-alt",`${this.t("MRTelegram.LegacySave")} · ${f.statLabel??""}`)}<p>${esc(f.description??"")}</p><p class="mrt-note">${esc(this.t("MRTelegram.LegacyReadOnly"))}</p>`;
    else if(f.kind==="save-result"){if(!game.user.isGM)return"";body=`${head("fa-eye",this.t("MRTelegram.LegacySave"))}<p>${esc(f.actorName??"")} · ${esc(f.statLabel??"")} ${f.target??""} · <b class="mrt-total">${f.total??""}</b> ${badge(!!f.success)}</p>`;}
    else if(f.kind==="save-reveal")body=`${head("fa-shield-alt",f.label??this.t("MRTelegram.LegacySave"))}<p>${f.revealMode==="full"?`<b class="mrt-total">${f.total}</b> `:""}${badge(!!f.success)}</p>`;
    else if(f.kind==="attachment-claim")body=`${head("fa-suitcase",this.t("MRTelegram.Claimed"))}<p>${esc(f.itemName)} → ${esc(f.actorName)}</p>`;
    else return"";
    const cont=prev&&fOf(prev)?.senderId===f.senderId&&time(m)-time(prev)<3e5?"cont":"";
    return `<article class="mrt-row ${mine?"me":"them"} ${f.pinned?"pinned":""} ${cont} ${card?"card":""} ${m.id===this.freshId?"fresh":""}" data-mid="${m.id}" data-kind="${f.kind}"><div class="mrt-bubble">${body}<small class="mrt-meta">${this.metaHTML(m)}</small></div>${this.msgTools(m)}</article>`;
  }
  renderCompose(){const box=this.root?.querySelector(".mrt-compose");if(!box)return;const ch=this.channelId();if(!ch){box.innerHTML="";return;}const draft=LocalStore.getDraft(ch),reply=LocalStore.getReply(ch);box.innerHTML=`${reply?`<div class="mrt-replybar"><span><b>${esc(reply.senderName)}</b> · ${esc(reply.text)}</span><button type="button" data-act="cancel-reply" aria-label="${esc(this.t("MRTelegram.Cancel"))}"><i class="fas fa-times" aria-hidden="true"></i></button></div>`:""}<div class="mrt-drop"><i class="fas fa-paperclip" aria-hidden="true"></i> ${esc(this.t("MRTelegram.DropHint"))}</div><div class="mrt-inputrow"><textarea class="mrt-input" rows="1" aria-label="${esc(this.t("MRTelegram.Placeholder"))}" placeholder="${esc(this.t("MRTelegram.Placeholder"))}">${esc(draft)}</textarea><button type="button" class="mrt-send" data-act="send" title="${esc(this.t("MRTelegram.Send"))}" aria-label="${esc(this.t("MRTelegram.Send"))}"><i class="fas fa-paper-plane" aria-hidden="true"></i></button></div>`;}
  async sendCurrent(){const input=this.root?.querySelector(".mrt-input");const text=input?.value??"";const p=this.currentPlayer();if(!p||!String(text).trim())return;const ch=this.channelId();const reply=LocalStore.getReply(ch);input.value="";LocalStore.clearDraft(ch);LocalStore.setReply(ch,null);this.renderCompose();try{await this.messages.sendText(p.id,text,reply);}catch(e){LocalStore.setDraft(ch,text);this.renderCompose();throw e;}}
  async onClick(e){const p=e.target.closest("[data-player]");if(p&&game.user.isGM){this.selectedPlayerId=p.dataset.player;this.loaded=0;this.renderAll();return;}const b=e.target.closest("[data-act]");if(!b)return;const a=b.dataset.act;
    if(a==="close")return this.close(); if(a==="send")return this.sendCurrent(); if(a==="older"){this.loaded+=this.pageSize();return this.renderThread({preserveScroll:true});}
    if(a==="reply"){const m=this.index.byId.get(b.dataset.mid);const f=fOf(m);LocalStore.setReply(this.channelId(),{messageId:m.id,senderName:game.users.get(f.senderId)?.name??this.t("MRTelegram.System"),text:this.summary(m,150)});this.renderCompose();return this.root.querySelector(".mrt-input")?.focus();}
    if(a==="cancel-reply"){LocalStore.setReply(this.channelId(),null);return this.renderCompose();}
    if(a==="pin"&&game.user.isGM){const m=this.index.byId.get(b.dataset.mid),f=fOf(m);await m.setFlag(MODULE_ID,FLAG_KEY,{...f,pinned:!f.pinned});return;}
    if(a==="jump"){this.root.querySelector(`.mrt-row[data-mid="${b.dataset.mid}"]`)?.scrollIntoView({block:"center",behavior:game.settings.get(MODULE_ID,"reduceMotion")?"auto":"smooth"});return;}
    if(a==="roll")return this.rollModal(); if(a==="mausritter-save")return this.mausritterSaveModal(); if(a==="execute-roll"){const m=this.index.byId.get(b.dataset.mid);await this.rolls.trigger(m);return;}
    if(a==="reveal-outcome"||a==="reveal-full"){const m=this.index.byId.get(b.dataset.mid);await this.rolls.reveal(m,a==="reveal-full"?"full":"outcome");return;}
    if(a==="open-doc"){const m=this.index.byId.get(b.dataset.mid);try{await openDocument(fOf(m)?.attachment?.uuid);}catch{ui.notifications.warn(this.t("MRTelegram.Errors.OpenDocument"));}return;}
    if(a==="open-link"){const u=fOf(this.index.byId.get(b.dataset.mid))?.attachment?.url;if(u)window.open(u,"_blank","noopener,noreferrer");return;}
    if(a==="claim"){const m=this.index.byId.get(b.dataset.mid),f=fOf(m);const already=this.index.messages(f.channelId,{visibleOnly:false}).some(x=>{const q=fOf(x);return q?.kind==="attachment-claim"&&q?.attachmentId===f.attachment?.id&&q?.senderId===game.user.id;});if(already)return ui.notifications.info(this.t("MRTelegram.AlreadyClaimed"));try{const actor=await claimItem(m,f);await this.messages.create({playerId:f.playerId,kind:"attachment-claim",data:{senderId:game.user.id,attachmentId:f.attachment.id,itemName:f.attachment.name,actorName:actor.name}});}catch{ui.notifications.error(this.t("MRTelegram.Errors.Claim"));}return;}
    if(a==="image"){const src=fOf(this.index.byId.get(b.dataset.mid))?.attachment?.src||fOf(this.index.byId.get(b.dataset.mid))?.attachment?.img;return this.modal(`<img class="mrt-image-modal" src="${esc(src)}">`);}
    if(a==="search")return this.searchModal(); if(a==="bulk")return this.bulkModal(); if(a==="templates")return this.templatesModal(); if(a==="notes")return this.notesModal(); if(a==="theme")return this.themeModal(); if(a==="access")return this.accessModal(); if(a==="clear")return this.clearCurrent(); if(a==="modal-close")return b.closest(".mrt-modal-wrap")?.remove();
  }
  modal(html){const w=document.createElement("div");w.className="mrt-modal-wrap";w.innerHTML=`<div class="mrt-modal" role="dialog" aria-modal="true">${html}<button type="button" class="mrt-modal-x" data-act="modal-close" aria-label="${esc(this.t("MRTelegram.Close"))}"><i class="fas fa-times" aria-hidden="true"></i></button></div>`;w.addEventListener("pointerdown",e=>{if(e.target===w)w.remove();});this.root.appendChild(w);w.querySelector("input:not([type=checkbox]),textarea,select")?.focus();return w;}
  rollModal(){if(!game.user.isGM)return ui.notifications.warn(this.t("MRTelegram.GMOnly"));const w=this.modal(`<h2>${esc(this.t("MRTelegram.SecretRoll"))}</h2><label>${esc(this.t("MRTelegram.Name"))}<input id="mrt-roll-label" value="${esc(this.t("MRTelegram.SecretRoll"))}"></label><label>${esc(this.t("MRTelegram.Description"))}<textarea id="mrt-roll-desc"></textarea></label><div class="mrt-grid"><label>${esc(this.t("MRTelegram.Formula"))}<input id="mrt-roll-formula" value="1d20"></label><label>${esc(this.t("MRTelegram.Resolution"))}<select id="mrt-roll-compare"><option value="lte">≤</option><option value="gte">≥</option><option value="none">—</option></select></label></div><label>${esc(this.t("MRTelegram.Target"))}<input id="mrt-roll-target" type="number" value="10"></label><label class="mrt-check"><input id="mrt-roll-show" type="checkbox"> ${esc(this.t("MRTelegram.ShowTarget"))}</label><button class="mrt-primary" id="mrt-roll-submit">${esc(this.t("MRTelegram.Send"))}</button>`);w.querySelector("#mrt-roll-submit").addEventListener("click",async()=>{const p=this.currentPlayer();await this.messages.requestRoll(p.id,{label:w.querySelector("#mrt-roll-label").value,description:w.querySelector("#mrt-roll-desc").value,formula:w.querySelector("#mrt-roll-formula").value,compare:w.querySelector("#mrt-roll-compare").value,target:Number(w.querySelector("#mrt-roll-target").value),showTarget:w.querySelector("#mrt-roll-show").checked});w.remove();});}
  mausritterSaveModal(){
    if(!game.user.isGM||!MausritterAdapter.matches())return; const p=this.currentPlayer(),actor=MausritterAdapter.actorForUser(p); if(!actor)return ui.notifications.error(this.t("MRTelegram.Errors.NoActor"));
    const rows=Object.entries(MausritterAdapter.stats).map(([k,v])=>`<option value="${k}">${esc(v.label)} · ${MausritterAdapter.statValue(actor,k)??"—"}</option>`).join("");
    const w=this.modal(`<h2>${esc(this.t("MRTelegram.MausritterSave"))}</h2><p>${esc(actor.name)}</p><label>${esc(this.t("MRTelegram.Attribute"))}<select id="mrt-ms-stat">${rows}</select></label><label>${esc(this.t("MRTelegram.Mode"))}<select id="mrt-ms-mode"><option value="normal">${esc(this.t("MRTelegram.ModeNormal"))}</option><option value="advantage">${esc(this.t("MRTelegram.ModeAdvantage"))}</option><option value="disadvantage">${esc(this.t("MRTelegram.ModeDisadvantage"))}</option></select></label><label>${esc(this.t("MRTelegram.Description"))}<textarea id="mrt-ms-desc"></textarea></label><button id="mrt-ms-send" class="mrt-primary">${esc(this.t("MRTelegram.Send"))}</button>`);
    w.querySelector("#mrt-ms-send").addEventListener("click",async()=>{const statKey=w.querySelector("#mrt-ms-stat").value,mode=w.querySelector("#mrt-ms-mode").value,abbr=MausritterAdapter.stats[statKey]?.label??statKey;await this.messages.requestRoll(p.id,{adapter:"mausritter",statKey,mode,label:`${abbr} ${this.t("MRTelegram.SaveWord")}`,description:w.querySelector("#mrt-ms-desc").value,formula:"1d20",compare:"lte",target:null,showTarget:false});w.remove();});
  }
  searchModal(){const w=this.modal(`<h2>${esc(this.t("MRTelegram.Search"))}</h2><input id="mrt-search-q" placeholder="${esc(this.t("MRTelegram.SearchPlaceholder"))}"><label class="mrt-check">${game.user.isGM?`<input id="mrt-search-all" type="checkbox"> ${esc(this.t("MRTelegram.SearchAll"))}`:""}</label><div class="mrt-search-results"></div>`);const run=()=>{const q=w.querySelector("#mrt-search-q").value.trim().toLocaleLowerCase();const all=w.querySelector("#mrt-search-all")?.checked;const msgs=(game.user.isGM&&all?this.index.all():this.index.messages(this.channelId())).filter(m=>this.summary(m,1000).toLocaleLowerCase().includes(q)).slice(-100).reverse();w.querySelector(".mrt-search-results").innerHTML=msgs.map(m=>`<button data-search-mid="${m.id}">${esc(this.summary(m,180))}</button>`).join("")||`<p>${esc(this.t("MRTelegram.NoResults"))}</p>`;for(const b of w.querySelectorAll("[data-search-mid]"))b.addEventListener("click",()=>{const m=this.index.byId.get(b.dataset.searchMid);const f=fOf(m);if(game.user.isGM)this.selectedPlayerId=f.playerId;w.remove();this.loaded=MAX_PAGE_SIZE;this.renderAll();requestAnimationFrame(()=>this.root.querySelector(`.mrt-row[data-mid="${m.id}"]`)?.scrollIntoView({block:"center"}));});};w.querySelector("#mrt-search-q").addEventListener("input",run);}
  bulkModal(){if(!game.user.isGM)return;const w=this.modal(`<h2>${esc(this.t("MRTelegram.Bulk"))}</h2><div class="mrt-recips">${this.players().map(p=>`<label><input type="checkbox" value="${p.id}"> ${esc(p.name)}</label>`).join("")}</div><textarea id="mrt-bulk-text"></textarea><button id="mrt-bulk-send" class="mrt-primary">${esc(this.t("MRTelegram.Send"))}</button>`);w.querySelector("#mrt-bulk-send").addEventListener("click",async()=>{const ids=[...w.querySelectorAll(".mrt-recips input:checked")].map(x=>x.value),text=w.querySelector("#mrt-bulk-text").value;if(ids.length&&text.trim()){await this.messages.sendBulk(ids,text);w.remove();}});}
  templates(){try{return JSON.parse(game.settings.get(MODULE_ID,"templates")||"[]");}catch{return[];}}
  templatesModal(){if(!game.user.isGM)return;const list=this.templates();const w=this.modal(`<h2>${esc(this.t("MRTelegram.Templates"))}</h2><div class="mrt-template-list">${list.map(t=>`<button data-tid="${t.id}"><b>${esc(t.label)}</b><span>${esc(t.text)}</span></button>`).join("")}</div><input id="mrt-tpl-label" placeholder="${esc(this.t("MRTelegram.Name"))}"><textarea id="mrt-tpl-text"></textarea><button id="mrt-tpl-add" class="mrt-primary">${esc(this.t("MRTelegram.Save"))}</button>`);for(const b of w.querySelectorAll("[data-tid]"))b.addEventListener("click",()=>{const t=list.find(x=>x.id===b.dataset.tid);LocalStore.setDraft(this.channelId(),t.text);w.remove();this.renderCompose();});w.querySelector("#mrt-tpl-add").addEventListener("click",async()=>{const label=w.querySelector("#mrt-tpl-label").value.trim(),text=w.querySelector("#mrt-tpl-text").value.trim();if(!label||!text)return;list.push({id:foundry.utils.randomID(),label,text});await game.settings.set(MODULE_ID,"templates",JSON.stringify(list.slice(-40)));w.remove();this.templatesModal();});}
  notesModal(){if(!game.user.isGM)return;const p=this.currentPlayer(),notes=this.index.messages(this.channelId(),{visibleOnly:false}).filter(m=>fOf(m)?.kind==="gm-note");const w=this.modal(`<h2>${esc(this.t("MRTelegram.Notes"))} · ${esc(p.name)}</h2><div class="mrt-notes">${notes.map(m=>`<p>${esc(fOf(m).note)}</p>`).join("")}</div><textarea id="mrt-note"></textarea><button id="mrt-note-add" class="mrt-primary">${esc(this.t("MRTelegram.Save"))}</button>`);w.querySelector("#mrt-note-add").addEventListener("click",async()=>{const n=w.querySelector("#mrt-note").value.trim();if(n){await this.messages.addNote(p.id,n);w.remove();this.notesModal();}});}
  themeModal(){const name=getThemeName();const w=this.modal(`<h2>${esc(this.t("MRTelegram.Theme.Title"))}</h2><div class="mrt-theme-grid">${Object.entries(THEMES).map(([k,v])=>`<button type="button" data-theme="${k}" class="${name===k?"sel":""}" aria-pressed="${name===k}"><span class="mrt-sw" style="background:${v.vars["--mrt-bg"]}"><i style="background:${v.vars["--mrt-incoming"]}"></i><i style="background:${v.vars["--mrt-outgoing"]}"></i><i style="background:${v.vars["--mrt-accent"]}"></i></span>${esc(this.t(v.label))}</button>`).join("")}<button type="button" data-theme="custom" class="${name==="custom"?"sel":""}" aria-pressed="${name==="custom"}">${esc(this.t("MRTelegram.Theme.Custom"))}</button></div><h3>${esc(this.t("MRTelegram.Theme.Editor"))}</h3>${["--mrt-bg","--mrt-panel","--mrt-text","--mrt-accent","--mrt-incoming","--mrt-outgoing","--mrt-in-text","--mrt-out-text"].map(k=>`<label>${esc(this.t("MRTelegram.Var."+k.slice(6)))}<input data-css-var="${k}" value="${esc(this.themeVars()[k]??"")}"></label>`).join("")}<button id="mrt-theme-save" class="mrt-primary">${esc(this.t("MRTelegram.SaveCustomTheme"))}</button>`);for(const b of w.querySelectorAll("[data-theme]"))b.addEventListener("click",async()=>{await game.settings.set(MODULE_ID,"theme",b.dataset.theme);this.applyTheme();w.remove();this.themeModal();});w.querySelector("#mrt-theme-save").addEventListener("click",async()=>{const vars={};for(const i of w.querySelectorAll("[data-css-var]"))vars[i.dataset.cssVar]=i.value;await game.settings.set(MODULE_ID,"customTheme",JSON.stringify(vars));await game.settings.set(MODULE_ID,"theme","custom");this.applyTheme();w.remove();});}
  accessModal(){const w=this.modal(`<h2>${esc(this.t("MRTelegram.Accessibility"))}</h2><label>${esc(this.t("MRTelegram.TextSize"))}<select id="mrt-a-scale"><option value="normal">A</option><option value="large">A+</option><option value="xl">A++</option></select></label><label class="mrt-check"><input id="mrt-a-contrast" type="checkbox"> ${esc(this.t("MRTelegram.HighContrast"))}</label><label class="mrt-check"><input id="mrt-a-reading" type="checkbox"> ${esc(this.t("MRTelegram.ReadingMode"))}</label><label class="mrt-check"><input id="mrt-a-motion" type="checkbox"> ${esc(this.t("MRTelegram.ReduceMotion"))}</label><button id="mrt-a-save" class="mrt-primary">${esc(this.t("MRTelegram.Apply"))}</button>`);w.querySelector("#mrt-a-scale").value=game.settings.get(MODULE_ID,"textScale");w.querySelector("#mrt-a-contrast").checked=game.settings.get(MODULE_ID,"highContrast");w.querySelector("#mrt-a-reading").checked=game.settings.get(MODULE_ID,"readingMode");w.querySelector("#mrt-a-motion").checked=game.settings.get(MODULE_ID,"reduceMotion");w.querySelector("#mrt-a-save").addEventListener("click",async()=>{await game.settings.set(MODULE_ID,"textScale",w.querySelector("#mrt-a-scale").value);await game.settings.set(MODULE_ID,"highContrast",w.querySelector("#mrt-a-contrast").checked);await game.settings.set(MODULE_ID,"readingMode",w.querySelector("#mrt-a-reading").checked);await game.settings.set(MODULE_ID,"reduceMotion",w.querySelector("#mrt-a-motion").checked);this.applyTheme();w.remove();});}
  async clearCurrent(){if(!game.user.isGM)return;const p=this.currentPlayer();if(!p)return;if(!confirm(this.t("MRTelegram.ConfirmClear",{name:p.name})))return;const ids=this.index.messages(this.channelId(),{visibleOnly:false}).map(m=>m.id);if(ids.length)await ChatMessage.deleteDocuments(ids);}
  onMessageCreate(m){const f=fOf(m);if(!f)return;this.freshId=m.id;const incoming=f.senderId&&f.senderId!==game.user.id;const current=f.channelId===this.channelId()&&this.root&&this.root.style.display!=="none";if(current){this.renderThread();this.renderPinned();this.markRead(f.channelId);}if(incoming){this.playSound();if(!current)ui.notifications.info(this.t("MRTelegram.NewPrivateMessage",{name:game.users.get(f.senderId)?.name??this.t("MRTelegram.System")}));}this.renderSidebar();this.updateLauncher(incoming&&!current);}
  onMessageUpdate(m){const f=fOf(m);if(!f)return;if(f.channelId===this.channelId()){this.renderThread({preserveScroll:true});this.renderPinned();}this.renderSidebar();this.updateLauncher();}
  onMessageDelete(m){const f=fOf(m);if(f?.channelId===this.channelId())this.renderThread({preserveScroll:true});this.renderSidebar();this.updateLauncher();}
  onRead(payload){this.liveReads.set(`${payload.userId}:${payload.channelId}`,payload.timestamp);if(payload.channelId===this.channelId())for(const row of this.root?.querySelectorAll(".mrt-row.me")??[]){const m=this.index.byId.get(row.dataset.mid),small=row.querySelector(".mrt-meta");if(m&&small)small.innerHTML=this.metaHTML(m);}}
}
